In [1]:
## imports
import numpy as np
from sklearn.model_selection import (
    StratifiedKFold,  # use X = np.zeros(n_samples) in .split
)
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier, NearestNeighbors

from data_img import Img_Obj_Dataset

# if you have indeces and want knns from large set, can make an idx array and NearestVectorCaller._call_vec_set; can just train/test split np.arange(len(ds)) to get back indeces for large sets


from btv import *

In [2]:
## Data setup

ds = Img_Obj_Dataset("data/hardhat/test", max_dim=128)
# can pass metric == "cosine", get from NearestVectorCaller.metric on large sets
knn = KNeighborsClassifier(weights="distance", n_neighbors=10) #, metric = "cosine")
# X, y = ds.whole_img_vec_set[:] # only need y for class balancing... ds.whole_img_vec_set.y

idx_train, idx_test = train_test_split(
    np.arange(len(ds.whole_img_vec_set)), test_size=0.2
)
X_train, y_train, X_test, y_test = ds.whole_img_vec_set.X[idx_train], ds.whole_img_vec_set.y[idx_train], ds.whole_img_vec_set.X[idx_test], ds.whole_img_vec_set.y[idx_test]

Detemining all classes...: 100%|██████████████████████████████| 1766/1766 [00:00<00:00, 2101.97it/s]


In [7]:
knn.fit(X_train, y_train)
# ds.whole_img_vec_set.X[idx_test]
knn.score(X_test,y_test)

KNeighborsClassifier(n_neighbors=10, weights='distance')

In [10]:
accuracy_score(
    ds.whole_img_vec_set.y[idx_test], knn.predict(ds.whole_img_vec_set.X[idx_test])
)

0.8107344632768362

In [9]:
# only include p if y==1 or, reeally, want p(right answer) so take elemnt of predicted prob indicated by binary y.
def prediction_entropy(y_true, y_predicted): # multilable
    # replace log(0) with n instead of -Inf
    if isinstance(y_predicted, list):
        y_predicted = np.stack(y_predicted, axis=1)
    A = np.zeros_like(y_true)
    with np.errstate(divide="ignore"):
        for i, (pred, true) in enumerate(zip(y_predicted, y_true)):
            for j, (p, t) in enumerate(zip(pred, true)):
                I = -np.log(p[t])
                if np.isinf(I):
                    I = y_true.size
                A[i, j] = I
    return np.mean(A, axis=0)


# probably actually want to do this at the prediction level since that is the big/slow bit.
def prediction_entropy_lg(y_true, y_predicted): # sinlge label
    # replace log(0) with n instead of -Inf
    if isinstance(y_predicted, list):
        y_predicted = np.stack(y_predicted, axis=1)
    with np.errstate(divide="ignore"):
        for pred, true in zip(y_predicted, y_true):
            for p, t in zip(pred, true):
                I = -np.log(p[t])
                if np.isinf(I):
                    I = y_true.size
                yield I

In [40]:
A = knn.predict(ds.whole_img_vec_set.X[idx_test])
P = knn.predict_proba(
    ds.whole_img_vec_set.X[idx_test]
)  # predicts the probability of each class. For whole image hardhats it is a list of 3 (p(no), P(yes)) arrays

In [41]:
prediction_entropy(y_predicted, y_true)

AttributeError: 'list' object has no attribute 'shape'

In [17]:
kfold_idx_gen = StratifiedKFold(n_splits=5).split(
    np.zeros(len(ds.whole_img_vec_set)), np.sum(ds.whole_img_vec_set.y, axis=1)
)
# can just add all the labels to make it multiclass for splitting
entropies = []
running_train = []
for k, (train_idx, test_idx) in enumerate(kfold_idx_gen):
    running_train.append(test_idx)
    # knn.fit(ds.whole_img_vec_set.X[train_idx], ds.whole_img_vec_set.y[train_idx])
    # y_predicted = knn.predict_proba(ds.whole_img_vec_set.X[test_idx])
    # y_true = ds.whole_img_vec_set.y[test_idx]
    # H = prediction_entropy(y_true, y_predicted)
    # entropies.append(H)
    # print(f"Fold : {k+1}, " f"Fold entropy : {H}")

In [20]:
np.mean(entropies, axis=0), np.std(entropies, axis=0), np.std(
    entropies, axis=0
) / np.mean(entropies, axis=0)

(array([75.04532578, 57.61076487, 16.80113314]),
 array([38.20580196, 28.99206553,  8.40056667]),
 array([0.50910302, 0.50324042, 0.50000001]))

In [188]:
knn.predict(ds.whole_img_vec_set.X[test_idx])

array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       ...,
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0]])

In [100]:
np.sum(ds.whole_img_vec_set.y, axis=0)

array([ 339, 1604,   45])

In [43]:
## with straigh vectorization of whole images, the knn accuracy goes down as more data is added. Therefore that vecotrization is shit. Maybe we try tabular data?

kfold_idx_gen = StratifiedKFold(n_splits=5).split(
    np.zeros(len(ds.whole_img_vec_set)), np.sum(ds.whole_img_vec_set.y, axis=1)
)
train_idx = np.array([], int)
running_train = []
for k, (_, test_idx) in enumerate(kfold_idx_gen):
    running_train.append(test_idx)
running_test = running_train.pop()
for k, old_test_idx in enumerate(running_train):
    train_idx = np.append(train_idx,old_test_idx)
    knn.fit(ds.whole_img_vec_set.X[train_idx], ds.whole_img_vec_set.y[train_idx])
    y_predicted = knn.predict_proba(ds.whole_img_vec_set.X[running_test])
    y_true = ds.whole_img_vec_set.y[running_test]
    H = prediction_entropy(y_true, y_predicted)
    entropies.append(H)
    print(f"Fold : {k+1}, " f"Test set entropy : {np.mean(H)}", f"Train samples : {len(train_idx)}", f"Accuracy : {accuracy_score(y_true,knn.predict(ds.whole_img_vec_set.X[test_idx]))}")

Fold : 1, Test set entropy : 45.036827195467424 Train samples : 354 Accuracy : 0.7705382436260623
Fold : 2, Test set entropy : 45.040604343720496 Train samples : 707 Accuracy : 0.7648725212464589
Fold : 3, Test set entropy : 47.038715769593956 Train samples : 1060 Accuracy : 0.7620396600566572
Fold : 4, Test set entropy : 52.03305004721435 Train samples : 1413 Accuracy : 0.7592067988668555


In [42]:
hs, ss = add_stratified_folds_test(ds.whole_img_vec_set.X,ds.whole_img_vec_set.y,knn)

ValueError: Supported target types are: ('binary', 'multiclass'). Got 'multilabel-indicator' instead.

In [ ]:
imc = ds.imc[:100]
color = len(imc[0].shape) > 2
channels = imc[0].shape[2] if color else 1
    
px_mean, px_std = np.zeros(channels), np.zeros(channels)
running_sum,running_sumsq  = 0,0 
for n, im in tqdm(
    enumerate(imc), desc="Scanning to find mean and STD of pixel values...", unit="Image file"
):

    last_px_mean = px_mean.copy()
    last_px_std = px_std.copy()
    px_mean += (im.mean(0).mean(0) - px_mean)/(n + 1)
    px_std = last_px_std**2 + ((im - last_px_mean)*(im - px_mean)) if n>0 else im.std(0).std(0)

    print(im.std(0).std(0), np.power(px_std,0.25))

NameError: name 'y_predicted' is not defined